use_frameworks!

platform :ios, '9.0'

target 'XKEFDevicePopView_Example' do
  pod 'XKEFDevicePopView', :path => '../'

  target 'XKEFDevicePopView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
